# Generated by Django 2.0.5 on 2018-07-17 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay2', '0007_auto_20180717_0841'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moves',
            new_name='Move',
        ),
    ]
