# Generated by Django 2.0.5 on 2018-07-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay2', '0011_auto_20180717_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='er',
            field=models.CharField(blank=True, default='sdf', max_length=300),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('D', 'Draw'), ('F', 'First PLayer Move'), ('S', 'Second PLayer Move')], default='F', max_length=1),
        ),
    ]
