# Generated by Django 2.0.5 on 2018-07-17 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay2', '0012_auto_20180717_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='chance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('by_first_player', models.BooleanField(default=True, editable=False)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('D', 'Draw'), ('S', 'Second PLayer Move'), ('F', 'First PLayer Move')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='chance',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay2.Game'),
        ),
    ]
