# Generated by Django 2.0.5 on 2018-07-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay2', '0013_auto_20180717_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='chance',
            name='er',
            field=models.CharField(blank=True, default='sdf', max_length=300),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('F', 'First PLayer Move'), ('D', 'Draw'), ('S', 'Second PLayer Move')], default='F', max_length=1),
        ),
    ]
