# Generated by Django 2.0.5 on 2018-07-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay2', '0014_auto_20180717_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chance',
            old_name='er',
            new_name='aer',
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('S', 'Second PLayer Move'), ('D', 'Draw'), ('F', 'First PLayer Move')], default='F', max_length=1),
        ),
    ]
