# Generated by Django 2.0.5 on 2018-07-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay2', '0015_auto_20180717_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('F', 'First PLayer Move'), ('S', 'Second PLayer Move'), ('D', 'Draw')], default='F', max_length=1),
        ),
    ]
