# Generated by Django 2.0.5 on 2018-07-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay2', '0016_auto_20180717_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chance',
            name='game',
        ),
        migrations.DeleteModel(
            name='chance',
        ),
    ]
