# Generated by Django 2.0.5 on 2018-07-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay2', '0018_auto_20180718_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('D', 'Draw'), ('W', 'First Player Wins'), ('F', 'First PLayer Move'), ('L', 'Second Player Wins'), ('S', 'Second Player To Move')], default='F', max_length=1),
        ),
    ]
