# Generated by Django 2.1.2 on 2018-10-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay2', '0020_auto_20181004_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('F', 'First PLayer Move'), ('S', 'Second Player To Move'), ('L', 'Second Player Wins'), ('W', 'First Player Wins'), ('D', 'Draw')], default='F', max_length=1),
        ),
    ]
