# Generated by Django 2.0.5 on 2018-07-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='invitation',
            name='image',
            field=models.CharField(default='/Users/neeraj/Desktop/download.jpeg', max_length=500),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='message',
            field=models.CharField(choices=[('f', 'Hello, wanna play withme?'), ('s', 'Lets play tictactoe')], max_length=300),
        ),
    ]
